services:
  - type: web
    name: chronos
    runtime: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: KAFKA_BROKERS
        value: ""
      - key: API_PORT
        value: "10000"
      - key: LOG_LEVEL
        value: info
